name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      # ⚠️ Comprueba que el secret realmente está disponible en el runner (sin imprimirlo)
      - name: Check API token presence
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_MUSHROOM_010FDBF0F }}" ]; then
            echo "❌ Token vacío o no accesible"; exit 1
          else
            echo "✅ Token presente"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: swa-db-connections/package-lock.json
          # Si tu app está en la raíz, cambia el path de cache a: package-lock.json

      - name: Install deps
        working-directory: swa-db-connections
        run: npm ci
        # Si tu app está en la raíz, quita working-directory

      - name: Build
        working-directory: swa-db-connections
        run: npm run build
        # Asegúrate que "build" genera la carpeta dist
        # Si tu app está en la raíz, quita working-directory

      # Verifica que el artefacto de build exista antes de subir
      - name: Verify build artifact
        run: |
          test -d "swa-db-connections/dist" || (echo "❌ No se generó swa-db-connections/dist"; exit 1)
        # Si tu app está en la raíz: test -d "dist"

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Usa tu secret actual. Cambiar el nombre aquí causará error si no renombras el secret en GitHub.
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_MUSHROOM_010FDBF0F }}
          action: upload

          ###### Rutas de tu proyecto (ajústalas si tu app está en raíz) ######
          app_location: "/"        # si tu app está en la raíz, usa: "/"
          api_location: ""                           # si usas Azure Functions, pon la carpeta
          output_location: "dist" # si tu app está en la raíz: "dist"
          ###### Fin de rutas ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close PR Environment
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
